// Code generated by Slice Machine. DO NOT EDIT.

import Courses from './Courses';
import ExchangeKnowledgeTeam from './ExchangeKnowledgeTeam';
import ExternalRepositories from './ExternalRepositories';
import GenerateKnowledgeTeam from './GenerateKnowledgeTeam';
import Hero from './Hero';
import ManageKnowledgeTeam from './ManageKnowledgeTeam';
import ManagementTeam from './ManagementTeam';
import Membership from './Membership';
import NavigationItem from './NavigationItem';
import NetworkMembers from './NetworkMembers';
import Objectives from './Objectives';
import Origin from './Origin';
import Repository from './Repository';
import ResearchLines from './ResearchLines';
import Social from './Social';
import TextBlock from './TextBlock';

export {
	Courses,
	ExchangeKnowledgeTeam,
	ExternalRepositories,
	GenerateKnowledgeTeam,
	Hero,
	ManageKnowledgeTeam,
	ManagementTeam,
	Membership,
	NavigationItem,
	NetworkMembers,
	Objectives,
	Origin,
	Repository,
	ResearchLines,
	Social,
	TextBlock,
};

export const components = {
	courses: Courses,
	exchange_knowledge_team: ExchangeKnowledgeTeam,
	external_repositories: ExternalRepositories,
	generate_knowledge_team: GenerateKnowledgeTeam,
	hero: Hero,
	manage_knowledge_team: ManageKnowledgeTeam,
	management_team: ManagementTeam,
	membership: Membership,
	navigation_item: NavigationItem,
	network_members: NetworkMembers,
	objectives: Objectives,
	origin: Origin,
	repository: Repository,
	research_lines: ResearchLines,
	social: Social,
	text_block: TextBlock,
};
