// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Membership from './Membership';
import NavigationItem from './NavigationItem';
import Objectives from './Objectives';
import Operation from './Operation';
import ResearchLines from './ResearchLines';
import Social from './Social';
import TextBlock from './TextBlock';

export {
	Hero,
	Membership,
	NavigationItem,
	Objectives,
	Operation,
	ResearchLines,
	Social,
	TextBlock,
};

export const components = {
	hero: Hero,
	membership: Membership,
	navigation_item: NavigationItem,
	objectives: Objectives,
	operation: Operation,
	research_lines: ResearchLines,
	social: Social,
	text_block: TextBlock,
};
