// Code generated by Slice Machine. DO NOT EDIT.

import ExchangeKnowledgeTeam from "./ExchangeKnowledgeTeam";
import GenerateKnowledgeTeam from "./GenerateKnowledgeTeam";
import Hero from "./Hero";
import ManageKnowledgeTeam from "./ManageKnowledgeTeam";
import ManagementTeam from "./ManagementTeam";
import Membership from "./Membership";
import NavigationItem from "./NavigationItem";
import NetworkMembers from "./NetworkMembers";
import Objectives from "./Objectives";
import Origin from "./Origin";
import ResearchLines from "./ResearchLines";
import Social from "./Social";
import TextBlock from "./TextBlock";

export {
  ExchangeKnowledgeTeam,
  GenerateKnowledgeTeam,
  Hero,
  ManageKnowledgeTeam,
  ManagementTeam,
  Membership,
  NavigationItem,
  NetworkMembers,
  Objectives,
  Origin,
  ResearchLines,
  Social,
  TextBlock,
};

export const components = {
  exchange_knowledge_team: ExchangeKnowledgeTeam,
  generate_knowledge_team: GenerateKnowledgeTeam,
  hero: Hero,
  manage_knowledge_team: ManageKnowledgeTeam,
  management_team: ManagementTeam,
  membership: Membership,
  navigation_item: NavigationItem,
  network_members: NetworkMembers,
  objectives: Objectives,
  origin: Origin,
  research_lines: ResearchLines,
  social: Social,
  text_block: TextBlock,
};
